/*
 * Mimepost
 * MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimepost) {
      root.Mimepost = {};
    }
    root.Mimepost.AccountProfile = factory(root.Mimepost.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AccountProfile model module.
   * @module model/AccountProfile
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>AccountProfile</code>.
   * @alias module:model/AccountProfile
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AccountProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountProfile} obj Optional instance to populate.
   * @return {module:model/AccountProfile} The populated <code>AccountProfile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('first_name'))
        obj.first_name = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.last_name = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('phone_number'))
        obj.phone_number = ApiClient.convertToType(data['phone_number'], 'String');
      if (data.hasOwnProperty('skype_id'))
        obj.skype_id = ApiClient.convertToType(data['skype_id'], 'String');
      if (data.hasOwnProperty('company_name'))
        obj.company_name = ApiClient.convertToType(data['company_name'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
      if (data.hasOwnProperty('twitter_handle'))
        obj.twitter_handle = ApiClient.convertToType(data['twitter_handle'], 'String');
      if (data.hasOwnProperty('linkedin'))
        obj.linkedin = ApiClient.convertToType(data['linkedin'], 'String');
      if (data.hasOwnProperty('billing_name'))
        obj.billing_name = ApiClient.convertToType(data['billing_name'], 'String');
      if (data.hasOwnProperty('billing_company_name'))
        obj.billing_company_name = ApiClient.convertToType(data['billing_company_name'], 'String');
      if (data.hasOwnProperty('billing_address'))
        obj.billing_address = ApiClient.convertToType(data['billing_address'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }

  /**
   * First name of the user
   * @member {String} first_name
   */
  exports.prototype.first_name = undefined;

  /**
   * Last name of the user
   * @member {String} last_name
   */
  exports.prototype.last_name = undefined;

  /**
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * @member {String} city
   */
  exports.prototype.city = undefined;

  /**
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * @member {String} phone_number
   */
  exports.prototype.phone_number = undefined;

  /**
   * @member {String} skype_id
   */
  exports.prototype.skype_id = undefined;

  /**
   * @member {String} company_name
   */
  exports.prototype.company_name = undefined;

  /**
   * @member {String} website
   */
  exports.prototype.website = undefined;

  /**
   * @member {String} twitter_handle
   * @default ''
   */
  exports.prototype.twitter_handle = '';

  /**
   * @member {String} linkedin
   */
  exports.prototype.linkedin = undefined;

  /**
   * @member {String} billing_name
   */
  exports.prototype.billing_name = undefined;

  /**
   * @member {String} billing_company_name
   */
  exports.prototype.billing_company_name = undefined;

  /**
   * @member {String} billing_address
   */
  exports.prototype.billing_address = undefined;

  /**
   * username
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * Account email address
   * @member {String} email
   */
  exports.prototype.email = undefined;


  return exports;

}));
