/*
 * Mimepost
 * MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimepost) {
      root.Mimepost = {};
    }
    root.Mimepost.ApiResponseDomainsListData = factory(root.Mimepost.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ApiResponseDomainsListData model module.
   * @module model/ApiResponseDomainsListData
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ApiResponseDomainsListData</code>.
   * @alias module:model/ApiResponseDomainsListData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ApiResponseDomainsListData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiResponseDomainsListData} obj Optional instance to populate.
   * @return {module:model/ApiResponseDomainsListData} The populated <code>ApiResponseDomainsListData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('domain'))
        obj.domain = ApiClient.convertToType(data['domain'], 'String');
      if (data.hasOwnProperty('selector'))
        obj.selector = ApiClient.convertToType(data['selector'], 'String');
      if (data.hasOwnProperty('instance_name'))
        obj.instance_name = ApiClient.convertToType(data['instance_name'], 'String');
      if (data.hasOwnProperty('spf_verified'))
        obj.spf_verified = ApiClient.convertToType(data['spf_verified'], 'Number');
      if (data.hasOwnProperty('dkim_verified'))
        obj.dkim_verified = ApiClient.convertToType(data['dkim_verified'], 'Number');
      if (data.hasOwnProperty('tracking_verified'))
        obj.tracking_verified = ApiClient.convertToType(data['tracking_verified'], 'Number');
      if (data.hasOwnProperty('verified'))
        obj.verified = ApiClient.convertToType(data['verified'], 'Number');
      if (data.hasOwnProperty('approved'))
        obj.approved = ApiClient.convertToType(data['approved'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('status_desc'))
        obj.status_desc = ApiClient.convertToType(data['status_desc'], 'String');
      if (data.hasOwnProperty('entered'))
        obj.entered = ApiClient.convertToType(data['entered'], 'String');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} domain
   */
  exports.prototype.domain = undefined;

  /**
   * @member {String} selector
   */
  exports.prototype.selector = undefined;

  /**
   * @member {String} instance_name
   */
  exports.prototype.instance_name = undefined;

  /**
   * @member {Number} spf_verified
   */
  exports.prototype.spf_verified = undefined;

  /**
   * @member {Number} dkim_verified
   */
  exports.prototype.dkim_verified = undefined;

  /**
   * @member {Number} tracking_verified
   */
  exports.prototype.tracking_verified = undefined;

  /**
   * @member {Number} verified
   */
  exports.prototype.verified = undefined;

  /**
   * @member {Number} approved
   */
  exports.prototype.approved = undefined;

  /**
   * @member {module:model/ApiResponseDomainsListData.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} status_desc
   */
  exports.prototype.status_desc = undefined;

  /**
   * @member {String} entered
   */
  exports.prototype.entered = undefined;

  /**
   * @member {Number} active
   */
  exports.prototype.active = undefined;



  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "WAITING_APPROVA"
     * @const
     */
    WAITING_APPROVA: "WAITING_APPROVA",

    /**
     * value: "NOT_VERIFIED"
     * @const
     */
    NOT_VERIFIED: "NOT_VERIFIED",

    /**
     * value: "APPROVED"
     * @const
     */
    APPROVED: "APPROVED"
  };

  return exports;

}));
