/*
 * Mimepost
 * MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimepost) {
      root.Mimepost = {};
    }
    root.Mimepost.ApiResponseEmaillogsData = factory(root.Mimepost.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ApiResponseEmaillogsData model module.
   * @module model/ApiResponseEmaillogsData
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ApiResponseEmaillogsData</code>.
   * @alias module:model/ApiResponseEmaillogsData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ApiResponseEmaillogsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiResponseEmaillogsData} obj Optional instance to populate.
   * @return {module:model/ApiResponseEmaillogsData} The populated <code>ApiResponseEmaillogsData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('datetime'))
        obj.datetime = ApiClient.convertToType(data['datetime'], 'String');
      if (data.hasOwnProperty('message_id'))
        obj.message_id = ApiClient.convertToType(data['message_id'], 'String');
      if (data.hasOwnProperty('to_email'))
        obj.to_email = ApiClient.convertToType(data['to_email'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} datetime
   */
  exports.prototype.datetime = undefined;

  /**
   * @member {String} message_id
   */
  exports.prototype.message_id = undefined;

  /**
   * @member {String} to_email
   */
  exports.prototype.to_email = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} details
   */
  exports.prototype.details = undefined;


  return exports;

}));
