/*
 * Mimepost
 * MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiResponseStatsDataDatewiseSummary', 'model/ApiResponseStatsDataGraphSummary', 'model/ApiResponseStatsDataTotalSummary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApiResponseStatsDataDatewiseSummary'), require('./ApiResponseStatsDataGraphSummary'), require('./ApiResponseStatsDataTotalSummary'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimepost) {
      root.Mimepost = {};
    }
    root.Mimepost.ApiResponseStatsData = factory(root.Mimepost.ApiClient, root.Mimepost.ApiResponseStatsDataDatewiseSummary, root.Mimepost.ApiResponseStatsDataGraphSummary, root.Mimepost.ApiResponseStatsDataTotalSummary);
  }
}(this, function(ApiClient, ApiResponseStatsDataDatewiseSummary, ApiResponseStatsDataGraphSummary, ApiResponseStatsDataTotalSummary) {
  'use strict';

  /**
   * The ApiResponseStatsData model module.
   * @module model/ApiResponseStatsData
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ApiResponseStatsData</code>.
   * @alias module:model/ApiResponseStatsData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ApiResponseStatsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiResponseStatsData} obj Optional instance to populate.
   * @return {module:model/ApiResponseStatsData} The populated <code>ApiResponseStatsData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('total_summary'))
        obj.total_summary = ApiResponseStatsDataTotalSummary.constructFromObject(data['total_summary']);
      if (data.hasOwnProperty('datewise_summary'))
        obj.datewise_summary = ApiResponseStatsDataDatewiseSummary.constructFromObject(data['datewise_summary']);
      if (data.hasOwnProperty('graph_summary'))
        obj.graph_summary = ApiResponseStatsDataGraphSummary.constructFromObject(data['graph_summary']);
    }
    return obj;
  }

  /**
   * @member {module:model/ApiResponseStatsDataTotalSummary} total_summary
   */
  exports.prototype.total_summary = undefined;

  /**
   * @member {module:model/ApiResponseStatsDataDatewiseSummary} datewise_summary
   */
  exports.prototype.datewise_summary = undefined;

  /**
   * @member {module:model/ApiResponseStatsDataGraphSummary} graph_summary
   */
  exports.prototype.graph_summary = undefined;


  return exports;

}));
