/*
 * Mimepost
 * MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimepost) {
      root.Mimepost = {};
    }
    root.Mimepost.ApiResponseStatsDataGraphSummary = factory(root.Mimepost.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ApiResponseStatsDataGraphSummary model module.
   * @module model/ApiResponseStatsDataGraphSummary
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ApiResponseStatsDataGraphSummary</code>.
   * @alias module:model/ApiResponseStatsDataGraphSummary
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ApiResponseStatsDataGraphSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiResponseStatsDataGraphSummary} obj Optional instance to populate.
   * @return {module:model/ApiResponseStatsDataGraphSummary} The populated <code>ApiResponseStatsDataGraphSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dates'))
        obj.dates = ApiClient.convertToType(data['dates'], ['String']);
      if (data.hasOwnProperty('status_counts'))
        obj.status_counts = ApiClient.convertToType(data['status_counts'], ['Number']);
    }
    return obj;
  }

  /**
   * @member {Array.<String>} dates
   */
  exports.prototype.dates = undefined;

  /**
   * @member {Array.<Number>} status_counts
   */
  exports.prototype.status_counts = undefined;


  return exports;

}));
