/*
 * Mimepost
 * MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@mimepost.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Mimepost);
  }
}(this, function(expect, Mimepost) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ApiResponseStatsDataTotalSummaryStatus', function() {
      beforeEach(function() {
        instance = new Mimepost.ApiResponseStatsDataTotalSummaryStatus();
      });

      it('should create an instance of ApiResponseStatsDataTotalSummaryStatus', function() {
        // TODO: update the code to test ApiResponseStatsDataTotalSummaryStatus
        expect(instance).to.be.a(Mimepost.ApiResponseStatsDataTotalSummaryStatus);
      });

      it('should have the property count (base name: "count")', function() {
        // TODO: update the code to test the property count
        expect(instance).to.have.property('count');
        // expect(instance.count).to.be(expectedValueLiteral);
      });

      it('should have the property perc (base name: "perc")', function() {
        // TODO: update the code to test the property perc
        expect(instance).to.have.property('perc');
        // expect(instance.perc).to.be(expectedValueLiteral);
      });

    });
  });

}));
